@extends('layouts.app') @php($edit=$vehiculo->exists)
@section('titulo',$edit?'Editar vehículo':'Nuevo vehículo') @section('encabezado',$edit?'Editar vehículo':'Nuevo vehículo') @section('subtitulo','Información técnica del automóvil')
@section('contenido')
<div class="card app-card mx-auto" style="max-width:900px"><div class="card-body p-4">@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ $edit?route('vehiculos.update',$vehiculo):route('vehiculos.store') }}">@csrf @if($edit)@method('PUT')@endif
<div class="row g-3"><div class="col-12"><label class="form-label">Cliente *</label><select class="form-select" name="cliente_id" required><option value="">Seleccionar propietario</option>@foreach($clientes as $c)<option value="{{ $c->id }}" @selected(old('cliente_id',$vehiculo->cliente_id)==$c->id)>{{ $c->nombre }} · {{ $c->ci_nit }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">Placa *</label><input class="form-control text-uppercase" name="placa" value="{{ old('placa',$vehiculo->placa) }}" required></div><div class="col-md-4"><label class="form-label">Marca *</label><input class="form-control" name="marca" value="{{ old('marca',$vehiculo->marca) }}" required></div><div class="col-md-4"><label class="form-label">Modelo *</label><input class="form-control" name="modelo" value="{{ old('modelo',$vehiculo->modelo) }}" required></div>
<div class="col-md-4"><label class="form-label">Año *</label><input type="number" class="form-control" name="anio" value="{{ old('anio',$vehiculo->anio?:now()->year) }}" required></div><div class="col-md-4"><label class="form-label">Color</label><input class="form-control" name="color" value="{{ old('color',$vehiculo->color) }}"></div><div class="col-md-4"><label class="form-label">Kilometraje *</label><input type="number" class="form-control" name="kilometraje" value="{{ old('kilometraje',$vehiculo->kilometraje??0) }}" min="0" required></div></div>
<div class="d-flex justify-content-end gap-2 mt-4"><a class="btn btn-light" href="{{ route('vehiculos.index') }}">Cancelar</a><button class="btn btn-primary">Guardar vehículo</button></div></form></div></div>
@endsection
