@extends('layouts.app')
@section('titulo','Repuestos') @section('encabezado','Repuestos e inventario') @section('subtitulo','Existencias, precios y alertas de stock')
@section('contenido')
<div class="d-flex justify-content-between mb-4"><h2 class="fw-bold">Inventario</h2><a class="btn btn-primary" href="{{ route('repuestos.create') }}"><i class="bi bi-plus-lg"></i> Nuevo repuesto</a></div>
<div class="card app-card mb-4"><div class="card-body"><form class="row g-2"><div class="col-md-8"><input class="form-control" name="buscar" value="{{ request('buscar') }}" placeholder="Código o nombre"></div><div class="col-md-2"><select class="form-select" name="alerta"><option value="">Todo</option><option value="stock" @selected(request('alerta')==='stock')>Stock bajo</option></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Filtrar</button></div></form></div></div>
<div class="card app-card"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Código</th><th>Repuesto</th><th>Proveedor</th><th>Stock</th><th>Mínimo</th><th>Precio</th><th>Estado</th><th></th></tr></thead><tbody>
@forelse($repuestos as $r)<tr class="{{ $r->stock_bajo?'table-warning':'' }}"><td class="fw-bold">{{ $r->codigo }}</td><td>{{ $r->nombre }}</td><td>{{ $r->proveedor?:'—' }}</td><td class="fw-bold">{{ $r->stock }} @if($r->stock_bajo)<i class="bi bi-exclamation-triangle text-danger" title="Stock bajo"></i>@endif</td><td>{{ $r->stock_minimo }}</td><td>Bs {{ number_format($r->precio,2) }}</td><td><span class="badge text-bg-{{ $r->activo?'success':'secondary' }}">{{ $r->activo?'Activo':'Inactivo' }}</span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('repuestos.edit',$r) }}"><i class="bi bi-pencil"></i></a> <form class="d-inline" method="POST" action="{{ route('repuestos.destroy',$r) }}" data-confirm="¿Eliminar este repuesto?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>
@empty<tr><td colspan="8" class="text-center py-5 text-secondary">No hay repuestos registrados.</td></tr>@endforelse</tbody></table></div>@if($repuestos->hasPages())<div class="card-footer bg-white">{{ $repuestos->links() }}</div>@endif</div>
@endsection
