@extends('layouts.app')
@section('titulo','Reportes') @section('encabezado','Reportes') @section('subtitulo','Indicadores operativos y financieros')
@section('contenido')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="fw-bold mb-1">Reporte de operaciones</h2><p class="text-secondary mb-0">Resultados calculados desde las órdenes registradas.</p></div><button class="btn btn-outline-primary" id="print-page"><i class="bi bi-printer me-1"></i>Imprimir</button></div>
<div class="card app-card mb-4"><div class="card-body"><form class="row g-3 align-items-end"><div class="col-md-5"><label class="form-label">Desde</label><input type="date" class="form-control" name="desde" value="{{ request('desde') }}"></div><div class="col-md-5"><label class="form-label">Hasta</label><input type="date" class="form-control" name="hasta" value="{{ request('hasta') }}"></div><div class="col-md-2"><button class="btn btn-primary w-100">Aplicar</button></div></form></div></div>
<div class="row g-3 mb-4">@foreach([['Órdenes',$metricas['ordenes'],'primary'],['Ingresos','Bs '.number_format($metricas['ingresos'],2),'success'],['Clientes',$metricas['clientes'],'info'],['Stock bajo',$metricas['stock_bajo'],'danger']] as [$n,$v,$c])<div class="col-6 col-xl-3"><div class="card app-card"><div class="card-body"><small class="text-secondary">{{ $n }}</small><div class="fs-3 fw-bold text-{{ $c }}">{{ $v }}</div></div></div></div>@endforeach</div>
<div class="row g-4"><div class="col-lg-4"><div class="card app-card h-100"><div class="card-body"><h5 class="fw-bold">Órdenes por estado</h5>@forelse($porEstado as $e)<div class="d-flex justify-content-between border-bottom py-3"><span>{{ $e->estado }}</span><strong>{{ $e->total }}</strong></div>@empty<p class="text-secondary mt-4">Sin datos para el periodo.</p>@endforelse</div></div></div>
<div class="col-lg-8"><div class="card app-card"><div class="table-responsive"><table class="table mb-0"><thead class="table-light"><tr><th>Orden</th><th>Fecha</th><th>Cliente</th><th>Vehículo</th><th>Estado</th><th>Total</th></tr></thead><tbody>@forelse($ordenes as $o)<tr><td>{{ $o->numero }}</td><td>{{ $o->fecha_ingreso->format('d/m/Y') }}</td><td>{{ $o->cliente->nombre }}</td><td>{{ $o->vehiculo->placa }}</td><td>{{ $o->estado }}</td><td>Bs {{ number_format($o->total,2) }}</td></tr>@empty<tr><td colspan="6" class="text-center py-4">Sin resultados.</td></tr>@endforelse</tbody></table></div>@if($ordenes->hasPages())<div class="card-footer bg-white">{{ $ordenes->links() }}</div>@endif</div></div></div>
@endsection
