@extends('layouts.app') @php($edit=$orden->exists)
@section('titulo',$edit?'Editar orden':'Nueva orden') @section('encabezado',$edit?'Editar orden':'Nueva orden') @section('subtitulo','Recepción, diagnóstico y seguimiento del trabajo')
@section('contenido')
<div class="card app-card mx-auto" style="max-width:1000px"><div class="card-body p-4">@if($errors->any())<div class="alert alert-danger"><strong>Revisa el formulario:</strong> {{ $errors->first() }}</div>@endif
<form method="POST" action="{{ $edit?route('ordenes.update',$orden):route('ordenes.store') }}">@csrf @if($edit)@method('PUT')@endif
<div class="row g-3"><div class="col-md-6"><label class="form-label">Cliente *</label><select class="form-select" name="cliente_id" required><option value="">Seleccionar</option>@foreach($clientes as $c)<option value="{{ $c->id }}" @selected(old('cliente_id',$orden->cliente_id)==$c->id)>{{ $c->nombre }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Vehículo *</label><select class="form-select" name="vehiculo_id" required><option value="">Seleccionar</option>@foreach($vehiculos as $v)<option value="{{ $v->id }}" @selected(old('vehiculo_id',$orden->vehiculo_id)==$v->id)>{{ $v->placa }} · {{ $v->marca }} {{ $v->modelo }} — {{ $v->cliente->nombre }}</option>@endforeach</select><div class="form-text">Debe pertenecer al cliente seleccionado.</div></div>
<div class="col-md-4"><label class="form-label">Fecha de ingreso *</label><input type="date" class="form-control" name="fecha_ingreso" value="{{ old('fecha_ingreso',$orden->fecha_ingreso?->format('Y-m-d')??now()->format('Y-m-d')) }}" required></div><div class="col-md-4"><label class="form-label">Entrega estimada</label><input type="date" class="form-control" name="fecha_entrega_estimada" value="{{ old('fecha_entrega_estimada',$orden->fecha_entrega_estimada?->format('Y-m-d')) }}"></div><div class="col-md-4"><label class="form-label">Entrega real</label><input type="date" class="form-control" name="fecha_entrega" value="{{ old('fecha_entrega',$orden->fecha_entrega?->format('Y-m-d')) }}"></div>
<div class="col-md-8"><label class="form-label">Estado *</label><select class="form-select" name="estado">@foreach(['Pendiente','En diagnóstico','En reparación','Finalizada','Entregada','Cancelada'] as $e)<option @selected(old('estado',$orden->estado?:'Pendiente')===$e)>{{ $e }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Total (Bs) *</label><input type="number" step=".01" min="0" class="form-control" name="total" value="{{ old('total',$orden->total??0) }}" required></div>
<div class="col-12"><label class="form-label">Problema reportado *</label><textarea class="form-control" rows="3" name="problema" required>{{ old('problema',$orden->problema) }}</textarea></div><div class="col-12"><label class="form-label">Diagnóstico técnico</label><textarea class="form-control" rows="4" name="diagnostico">{{ old('diagnostico',$orden->diagnostico) }}</textarea></div></div>
<div class="d-flex justify-content-end gap-2 mt-4"><a class="btn btn-light" href="{{ route('ordenes.index') }}">Cancelar</a><button class="btn btn-primary">Guardar orden</button></div></form></div></div>
@endsection
