@extends('layouts.app')
@section('titulo','Órdenes') @section('encabezado','Órdenes de trabajo') @section('subtitulo','Seguimiento de reparaciones y diagnósticos')
@section('contenido')
<div class="d-flex justify-content-between mb-4"><h2 class="fw-bold">Órdenes de trabajo</h2><a class="btn btn-primary" href="{{ route('ordenes.create') }}"><i class="bi bi-plus-lg"></i> Nueva orden</a></div>
<div class="card app-card mb-4"><div class="card-body"><form class="row g-2"><div class="col-md-7"><input class="form-control" name="buscar" value="{{ request('buscar') }}" placeholder="Número de orden o cliente"></div><div class="col-md-3"><select class="form-select" name="estado"><option value="">Todos los estados</option>@foreach(['Pendiente','En diagnóstico','En reparación','Finalizada','Entregada','Cancelada'] as $e)<option @selected(request('estado')===$e)>{{ $e }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-primary w-100">Filtrar</button></div></form></div></div>
<div class="card app-card"><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Orden</th><th>Cliente</th><th>Vehículo</th><th>Ingreso</th><th>Estado</th><th>Total</th><th></th></tr></thead><tbody>
@forelse($ordenes as $o)<tr><td class="fw-bold text-primary">{{ $o->numero }}</td><td>{{ $o->cliente->nombre }}</td><td><span class="badge text-bg-dark">{{ $o->vehiculo->placa }}</span><br><small>{{ $o->vehiculo->marca }} {{ $o->vehiculo->modelo }}</small></td><td>{{ $o->fecha_ingreso->format('d/m/Y') }}</td><td><span class="badge text-bg-{{ in_array($o->estado,['Finalizada','Entregada'])?'success':($o->estado==='Cancelada'?'danger':'warning') }}">{{ $o->estado }}</span></td><td>Bs {{ number_format($o->total,2) }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('ordenes.edit',$o) }}"><i class="bi bi-pencil"></i></a> <form class="d-inline" method="POST" action="{{ route('ordenes.destroy',$o) }}" data-confirm="¿Eliminar esta orden?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>
@empty<tr><td colspan="7" class="text-center py-5 text-secondary">No hay órdenes registradas.</td></tr>@endforelse</tbody></table></div>@if($ordenes->hasPages())<div class="card-footer bg-white">{{ $ordenes->links() }}</div>@endif</div>
@endsection
